version: 0.2

phases:
  install: 
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.14.0/terraform_1.14.0_linux_amd64.zip"
      - "unzip -o terraform.zip"

  pre_build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false 
      - terraform plan -input=false
  build:
    commands:
      - terraform apply -input=false -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*' 